spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BlessingChess?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false
    username: root
    password: 123456
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 5MB
uploadDirectory: E:/StudentOnline/BlessingChess/image/
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
